#!/bin/sh
set -ux

systemctl status kubelet > $DEBUG_SCRIPT_DIR/kubelet-systemctl-status
journalctl -u kubelet > $DEBUG_SCRIPT_DIR/kubelet-journal

mkdir -p $DEBUG_SCRIPT_DIR/etc-default
cp /etc/default/kube* $DEBUG_SCRIPT_DIR/etc-default

mkdir -p $DEBUG_SCRIPT_DIR/lib-systemd-system
cp /lib/systemd/system/kube* $DEBUG_SCRIPT_DIR/lib-systemd-system
