#!/bin/bash

set -ex

# Grab the action parameter values
FOCUS=$(action-get focus)
SKIP=$(action-get skip)
PARALLELISM=$(action-get parallelism)

if [ ! -f /home/ubuntu/.kube/config ]
then
  action-fail "Missing Kubernetes configuration."
  action-set suggestion="Relate to the certificate authority, and kubernetes-master"
  exit 0
fi

# get the host from the config file
SERVER=$(cat /home/ubuntu/.kube/config | grep server | sed 's/    server: //')

ACTION_HOME=/home/ubuntu
ACTION_LOG=$ACTION_HOME/${JUJU_ACTION_UUID}.log
ACTION_LOG_TGZ=$ACTION_LOG.tar.gz
ACTION_JUNIT=$ACTION_HOME/${JUJU_ACTION_UUID}-junit
ACTION_JUNIT_TGZ=$ACTION_JUNIT.tar.gz

ginkgo -nodes=$PARALLELISM $(which e2e.test) -- \
  -kubeconfig /home/ubuntu/.kube/config \
  -host $SERVER \
  -ginkgo.focus $FOCUS \
  -ginkgo.skip "$SKIP" \
  -report-dir $ACTION_JUNIT 2>&1 | tee $ACTION_LOG

tar -czf $ACTION_LOG_TGZ $ACTION_LOG
tar -czf $ACTION_JUNIT_TGZ $ACTION_JUNIT

action-set log="$ACTION_LOG_TGZ"
action-set junit="$ACTION_JUNIT_TGZ"
